### ISSUE TITLE
Bạn còn phát triển zigatool không

### ISSUE THREAD

**Issue by haison8x** [wawahuy/react-horizontal-vertical#3]
Chào Huy
Tôi thấy bạn ở đây https://github.com/wawahuy/ziga-tool-v2

Đáng tiếc là zigavn cờ tướng đã up lên coco nên không xài được nữa
Tuy nhiên nếu sử dụng chức năng override javascript thì có thể in ra bàn cờ như hình tôi gửi
Tôi nghĩ vẫn có thể tiếp tục viết bot được
![board](https://github.com/wawahuy/react-horizontal-vertical/assets/3090475/6b8bd458-2247-42e0-a221-6e3770b25769)

**Comment by wawahuy** [comment]
I am currently not developing Ziga anymore, so I think you should raise this issue at https://github.com/wawahuy/ziga-tool-v2.
It's not that further modifications are impossible, but due to the low number of users, I am not continuing development.
Telegram: https://t.me/wawahuy
